export interface NavItem {
  label: string;
  path: string;
  children?: NavItem[];
}

export const navItems: NavItem[] = [
  { label: "Home", path: "/" },
  {
    label: "About Us",
    path: "#",
    children: [
      { label: "Chairman", path: "/about-us/chairman" },
      { label: "CEO", path: "/about-us/ceo" },
      { label: "Rector", path: "/about-us/rector" },
      { label: "Principal", path: "/about-us/principal" },
      { label: "Administration", path: "/about-us/administration" },
      { label: "Statutory Approvals", path: "/about-us/statutory-approvals" },
      { label: "Accreditation", path: "/about-us/accreditation" },
      { label: "Center of Excellence", path: "/about-us/center-of-excellence" },
      { label: "Rankings and Certifications", path: "/about-us/rankings-certifications" },
      { label: "Awards & Accolades", path: "/about-us/awards-accolades" },
      { label: "Strategic Plan", path: "/about-us/strategic-plan" },
    ],
  },
  {
    label: "Governance",
    path: "#",
    children: [
      { label: "Organizational Structure", path: "/governance/organizationalStructure" },
      { label: "Governing Body", path: "/governance/governingBody" },
      { label: "Academic Council", path: "/governance/academicCouncil" },
      { label: "Finance Committee", path: "/governance/financeCommittee" },
      {
        label: "Non Statutory nonStatutoryCommittees",
        path: "/governance/nonStatutoryCommittees",
        children: [
          { label: "Planning and Monitoring committee (PMC)", path: "/governance/nonStatutoryCommittees/planningAndMonitoringCommittee" },
          { label: "Academic Planning and Monitoring committee (APMC)", path: "/governance/nonStatutoryCommittees/academicPlanningAndMonitoringCommittee" },
          { label: "Admission Advisory committee (AAC)", path: "/governance/nonStatutoryCommittees/admissionAdvisoryCommittee" },
          { label: "Research & Development Advisory committee (R&D AC)", path: "/governance/nonStatutoryCommittees/researchAndDevelopmentAdvisoryCommittee" },
          { label: "Examination Evaluation Committee (EEC)", path: "/governance/nonStatutoryCommittees/examinationEvaluationCommittee" },
          { label: "Training and Placement Committee (T&PC)", path: "/governance/nonStatutoryCommittees/trainingAndPlacementCommittee" },
          { label: "Code of Conduct Monitoring Committee (CCMC)", path: "/governance/nonStatutoryCommittees/codeOfConductMonitoringCommittee" },
          { label: "Grievance Redressal Committee (GRC)", path: "/governance/nonStatutoryCommittees/grievanceRedressalCommittee" },
          { label: "Internal Complaints Committee (ICC)", path: "/governance/nonStatutoryCommittees/internalComplaintsCommittee" },
          { label: "Purchase Committee (PC)", path: "/governance/nonStatutoryCommittees/purchaseCommittee" },
          { label: "Library Advisory Committee (LAC)", path: "/governance/nonStatutoryCommittees/libraryAdvisoryCommittee" },
          { label: "Hostel Management Committee (HMC)", path: "/governance/nonStatutoryCommittees/hostelManagementCommittee" },
          { label: "Research Ethics Committee (REC)", path: "/governance/nonStatutoryCommittees/researchAndDevelopmentAdvisoryCommittee" },
          { label: "SC & ST Committee (SC&ST C)", path: "/governance/nonStatutoryCommittees/SCAndSTCommittee" },
          { label: "Student Activity Committee (SAC)", path: "/governance/nonStatutoryCommittees/studentActivityCommittee" },
          { label: "Student Welfare Committee (SWC)", path: "/governance/nonStatutoryCommittees/studentWelfareCommittee" },
          { label: "Anti Ragging Committee (ARC)", path: "/governance/nonStatutoryCommittees/antiRaggingCommittee" },
          { label: "Academic and Administrative Audit Committee (AAAC)", path: "/governance/nonStatutoryCommittees/academicAndAdministrativeAuditCommittee" },
          { label: "Department Development Committee (DDC)", path: "/governance/nonStatutoryCommittees/departmentDevelopmentCommittee" },
        ],
      },
    ],
  },
  {
    label: "Academics",
    path: "#",
    children: [
      {
        label: "Admissions",
        path: "/academics/Admissions",
        children: [
          { label: "Courses Offered", path: "/academics/Admissions/coursesoffered" },
          { label: "Admission Procedure", path: "/academics/Admissions/admissionproduce" },
          { label: "Admission Lists", path: "/academics/Admissions/admissionlist" },
          { label: "Course Outcomes", path: "/academics/Admissions/courseoutcome" },
        ],
      },
      { label: "Academic Calendars", path: "/academics/Admissions/academiccalender" },
      {
        label: "Teaching Learning Process",
        path: "/academics/teachinglearning",
        children: [
          { label: "Teaching Methodologies", path: "/academics/teachinglearning/teachingmethod" },
          { label: "OBE Practices", path: "/academics/teachinglearning/obepractice" },
          { label: "Special Programs - Student Diversity", path: "/academics/teachinglearning/specialprogram" },
          { label: "Mentor-Mentee System", path: "/academics/teachinglearning/mentor-mentee" },
        ],
      },
      { label: "Internship Manual", path: "https://vignaniit.edu.in/Internship%20manual%20and%20student%20diary.pdf" },
      { label: "Exit Students Feedback", path: "https://vignaniit.edu.in/Exit%20Feed%20Back.pdf" },
      { label: "MoUs - Academics", path: "https://vignaniit.edu.in/naac/criteria1/1.1.3%20Attachments/MoUs/1.1.3_VIIT_MoUs_Academics.pdf" },
      { label: "Extra Curricular Activities", path: "https://vignaniit.edu.in/ssr/criteria5/5.3.1/5.3.1_Website%20Copy-1.pdf"},
      { label: "POs, PEOs and PSOs", path: "https://vignaniit.edu.in/ssr/criteria1/1.1.1/1.1.1%20b.pdf" },
      { label: "Curriculum Design Process", path: "https://vignaniit.edu.in/ssr/criteria1/1.1.1/1.%201%20.1%20a%20.pdf" },
      { label: "Internships Projects and Research Projects", path: "/academics/internshipprojects" },
    ],
  },
  {
    label: "Departments",
    path: "#",
    children: [
      { label: "Civil Engineering", path: "/Departments/Civil" },
      { label: "Electrical & Electronics Engg.", path: "/Departments/EEE" },
      { label: "Mechanical Engineering", path: "/Departments/ME" },
      { label: "Electronics and Communication Engineering", path: "/Departments/ECE" },
      { label: "Computer Science & Engineering", path: "/Departments/CSE" },
      { label: "Advanced Computer Science & Engineering", path: "/Departments/ACSE" },
      { label: "Information Technology", path: "/Departments/IT" },
      { label: "Electronics & Computer Engineering", path: "/Departments/ECM" },
      { label: "Artificial Intelligence & DataScience", path: "/Departments/AIDS" },
      { label: "Basic Science & Humanities", path: "/Departments/BSH" },
      { label: "Management Studies", path: "/Departments/MBA" },
      { label: "Master of Computer Applications", path: "/Departments/MCA" },

    ],
  },
  {
    label: "Placements",
    path: "#",
    children: [
      { label: "About T&P", path: "/placements/abouttp" },
      { label: "Placement Details", path: "/placements/placementdetails" },
      { label: "Training Process", path: "/placements/trainingprocess" },
      { label: "Contact", path: "/placements/contact" },
    ],
  },
  {
    label: "Examinations",
    path: "#",
    children: [
      { label: "Time Tables", path: "/examinations/Timetable" },
      { label: "Notifications", path: "/examinations/notifications" },
      { label: "Examination Manual", path: "https://vignaniit.edu.in/examcell/regulations/Examination%20Manual.pdf" },
      { label: "It Reforms", path: "https://vignaniit.edu.in/examcell/IT%20Integrations.pdf" },
      { label: "About Exam Cell", path: "/examinations/aboutexamcell" },
      { label: "Results", path: "/examinations/results" },
      
      
    ],
  },
  {
    label: "Facilities",
    path: "#",
    children: [
      {
        label: "Infrastructure Facilities",
        path: "/facilities/infrastructure",
        children: [
          { label: "Teaching Learning Facilities", path: "/facilities/infrastructure/teaching-learning" },
          { label: "ICT Enabled Facilities", path: "/facilities/infrastructure/ict-enabled" },
          { label: "Cultural & Sports Facilities", path: "/facilities/infrastructure/cultural-sports" },
          { label: "Alternative Energy Sources", path: "/facilities/infrastructure/energy-sources" },
          { label: "Waste Management Facility", path: "/facilities/infrastructure/waste-management" },
          { label: "Water Conservation Facility", path: "/facilities/infrastructure/water-conservation" },
          { label: "Other Facilities", path: "/facilities/infrastructure/other" },
        ],
      },
      { label: "Library", path: "/facilities/library" },
      { label: "IT Infrastructure", path: "/facilities/it-infrastructure" },
      { label: "Lecture Capturing Facilities", path: "/facilities/lecture-capture" },
      { label: "Transport", path: "/facilities/transport" },
      { label: "Hostels", path: "/facilities/hostels" },
      { label: "Cafeteria", path: "/facilities/cafeteria" },
      { label: "Physical Education", path: "/facilities/physical-education" },
      { label: "Medical", path: "/facilities/medical" },
    ],
  },
  {
    label: "Cells",
    path: "#",
    children: [
      { label: "Discipline Cell", path: "/cells/discipline" },
      { label: "ED Cell", path: "/cells/ed" },
      { label: "Green Club", path: "/cells/green-club" },
      { label: "Idea Lab", path: "/cells/idea-lab" },
      { label: "IIC Cell", path: "/cells/iic" },
      { label: "IPR Cell", path: "/cells/ipr" },
      { label: "International Student Cell", path: "/cells/international-student" },
      { label: "IEEE Chapter", path: "/cells/ieee-chapter" },
      { label: "Media Cell", path: "/cells/media" },
      { label: "NSS Unit", path: "/cells/nss" },
      { label: "Research Cell", path: "/cells/research" },
      { label: "Skill Development Lab", path: "/cells/skill-development" },
      { label: "Student Activity Council", path: "/cells/student-activity-council" },
      { label: "WEP Cell", path: "/cells/wep" },
    ],
  },
  { label: "Contact Us", path: "/contactus" },
];
