export interface NavItem {
  label: string;
  path: string;
  children?: NavItem[];
}

export const navItems: NavItem[] = [
  { label: "Home", path: "/" },
  {
    label: "About Us",
    path: "/about-us",
    children: [
      { label: "Vision & Mission", path: "/about-us/vision-mission" },
      { label: "Chairman", path: "/about-us/chairman" },
      { label: "CEO", path: "/about-us/ceo" },
      { label: "Rector", path: "/about-us/rector" },
      { label: "Principal", path: "/about-us/principal" },
      { label: "Administration", path: "/about-us/administration" },
      { label: "Statutory Approvals", path: "/about-us/statutory-approvals" },
      { label: "Accreditation", path: "/about-us/accreditation" },
      { label: "Center of Excellence", path: "/about-us/center-of-excellence" },
      { label: "Rankings and Certifications", path: "/about-us/rankings-certifications" },
      { label: "Awards & Accolades", path: "/about-us/awards-accolades" },
      { label: "Strategic Plan", path: "/about-us/strategic-plan" },
    ],
  },
  {
    label: "Governance",
    path: "/governance",
    children: [
      { label: "Organizational Structure", path: "/governance/organizational-structure" },
      { label: "Governing Body", path: "/governance/governing-body" },
      { label: "Academic Council", path: "/governance/academic-council" },
      { label: "Finance Committee", path: "/governance/finance-committee" },
      {
        label: "Non Statutory Committees",
        path: "/governance/non-statutory-committees",
        children: [
          { label: "Planning and Monitoring committee (PMC)", path: "/governance/committees/pmc" },
          { label: "Academic Planning and Monitoring committee (APMC)", path: "/governance/committees/apmc" },
          { label: "Admission Advisory committee (AAC)", path: "/governance/committees/aac" },
          { label: "Research & Development Advisory committee (R&D AC)", path: "/governance/committees/rd-ac" },
          { label: "Examination Evaluation Committee (EEC)", path: "/governance/committees/eec" },
          { label: "Training and Placement Committee (T&PC)", path: "/governance/committees/tpc" },
          { label: "Code of Conduct Monitoring Committee (CCMC)", path: "/governance/committees/ccmc" },
          { label: "Grievance Redressal Committee (GRC)", path: "/governance/committees/grc" },
          { label: "Internal Complaints Committee (ICC)", path: "/governance/committees/icc" },
          { label: "Purchase Committee (PC)", path: "/governance/committees/pc" },
          { label: "Library Advisory Committee (LAC)", path: "/governance/committees/lac" },
          { label: "Hostel Management Committee (HMC)", path: "/governance/committees/hmc" },
          { label: "Research Ethics Committee (REC)", path: "/governance/committees/rec" },
          { label: "SC & ST Committee (SC&ST C)", path: "/governance/committees/sc-st-c" },
          { label: "Student Activity Committee (SAC)", path: "/governance/committees/sac" },
          { label: "Student Welfare Committee (SWC)", path: "/governance/committees/swc" },
          { label: "Anti Ragging Committee (ARC)", path: "/governance/committees/arc" },
          { label: "Academic and Administrative Audit Committee (AAAC)", path: "/governance/committees/aaac" },
          { label: "Department Development Committee (DDC)", path: "/governance/committees/ddc" },
        ],
      },
    ],
  },
  {
    label: "Academics",
    path: "/academics",
    children: [
      {
        label: "Admissions",
        path: "/academics/admissions",
        children: [
          { label: "Courses Offered", path: "/academics/admissions/courses-offered" },
          { label: "Admission Procedure", path: "/academics/admissions/procedure" },
          { label: "Admission Lists", path: "/academics/admissions/lists" },
          { label: "Course Outcomes", path: "/academics/admissions/outcomes" },
        ],
      },
      { label: "Academic Calendars", path: "/academics/calendars" },
      {
        label: "Teaching Learning Process",
        path: "/academics/teaching-learning-process",
        children: [
          { label: "Teaching Methodologies", path: "/academics/tlp/methodologies" },
          { label: "OBE Practices", path: "/academics/tlp/obe-practices" },
          { label: "Special Programs - Student Diversity", path: "/academics/tlp/special-programs" },
          { label: "Mentor-Mentee System", path: "/academics/tlp/mentor-mentee" },
        ],
      },
      { label: "Internship Manual", path: "/academics/internship-manual" },
      { label: "Exit Students Feedback", path: "/academics/student-feedback" },
      { label: "MoUs - Academics", path: "/academics/mous" },
      {
        label: "Extra Curricular Activities",
        path: "/academics/extra-curricular",
        children: [
          { label: "Glimpse of Sports and Culturals", path: "/academics/extra-curricular/sports-culturals" },
        ]
      },
      { label: "POs, PEOs and PSOs", path: "/academics/pos-peos-psos" },
      { label: "Curriculum Design Process", path: "/academics/curriculum-design" },
      { label: "Internships Projects and Research Projects", path: "/academics/internships-research" },
    ],
  },
  {
    label: "Departments",
    path: "/departments",
    children: [
      { label: "Civil Engineering", path: "/departments/civil" },
      { label: "Electrical & Electronics Engg.", path: "/departments/eee" },
      { label: "Mechanical Engineering", path: "/departments/mech" },
      { label: "Electronics and Communication Engineering", path: "/departments/ece" },
      { label: "Computer Science & Engineering", path: "/departments/cse" },
      { label: "Advanced Computer Science & Engineering", path: "/departments/cse-advanced" },
      { label: "Information Technology", path: "/departments/it" },
      { label: "Electronics & Computer Engineering", path: "/departments/ecm" },
      { label: "Artificial Intelligence & DataScience", path: "/departments/ai-ds" },
      { label: "Basic Science & Humanities", path: "/departments/bsh" },
      { label: "Management Studies", path: "/departments/mba" },
      { label: "Master of Computer Applications", path: "/departments/mca" },
    ],
  },
  {
    label: "Placements",
    path: "/placements",
    children: [
      { label: "About T&P", path: "/placements/about" },
      { label: "Placement Details", path: "/placements/details" },
      { label: "Training Process", path: "/placements/training" },
      { label: "Contact", path: "/placements/contact" },
    ],
  },
  {
    label: "Examinations",
    path: "/examinations",
    children: [
      { label: "Notifications", path: "/examinations/notifications" },
      { label: "Results", path: "/examinations/results" },
      { label: "Time Tables", path: "/examinations/time-tables" },
      { label: "Contact", path: "/examinations/contact" },
    ],
  },
  {
    label: "Facilities",
    path: "/facilities",
    children: [
      {
        label: "Infrastructure Facilities",
        path: "/facilities/infrastructure",
        children: [
          { label: "Teaching Learning Facilities", path: "/facilities/infrastructure/teaching-learning" },
          { label: "ICT Enabled Facilities", path: "/facilities/infrastructure/ict-enabled" },
          { label: "Cultural & Sports Facilities", path: "/facilities/infrastructure/cultural-sports" },
          { label: "Alternative Energy Sources", path: "/facilities/infrastructure/energy-sources" },
          { label: "Waste Management Facility", path: "/facilities/infrastructure/waste-management" },
          { label: "Water Conservation Facility", path: "/facilities/infrastructure/water-conservation" },
          { label: "Other Facilities", path: "/facilities/infrastructure/other" },
        ],
      },
      { label: "Library", path: "/facilities/library" },
      { label: "IT Infrastructure", path: "/facilities/it-infrastructure" },
      { label: "Lecture Capturing Facilities", path: "/facilities/lecture-capture" },
      { label: "Transport", path: "/facilities/transport" },
      { label: "Hostels", path: "/facilities/hostels" },
      { label: "Cafeteria", path: "/facilities/cafeteria" },
      { label: "Physical Education", path: "/facilities/physical-education" },
      { label: "Medical", path: "/facilities/medical" },
    ],
  },
  {
    label: "Cells",
    path: "/cells",
    children: [
      { label: "Discipline Cell", path: "/cells/discipline" },
      { label: "ED Cell", path: "/cells/ed" },
      { label: "Green Club", path: "/cells/green-club" },
      { label: "Idea Lab", path: "/cells/idea-lab" },
      { label: "IIC Cell", path: "/cells/iic" },
      { label: "IPR Cell", path: "/cells/ipr" },
      { label: "International Student Cell", path: "/cells/international-student" },
      { label: "IEEE Chapter", path: "/cells/ieee-chapter" },
      { label: "Media Cell", path: "/cells/media" },
      { label: "NSS Unit", path: "/cells/nss" },
      { label: "Research Cell", path: "/cells/research" },
      { label: "Skill Development Lab", path: "/cells/skill-development" },
      { label: "Student Activity Council", path: "/cells/student-activity-council" },
      { label: "WEP Cell", path: "/cells/wep" },
    ],
  },
  { label: "Contact Us", path: "/contact-us" },
];
